subjects = {
    "Physical sciences": [
        "Materials science",
        "Chemistry",
        "Physics",
        "Nanoscience and technology",
        "Optics and photonics",
        "Engineering",
        "Energy science and technology",
        "Mathematics and computing",
        "Astronomy and planetary science"
    ],
    "Earth and environmental sciences": [
        "Ecology",
        "Climate sciences",
        "Solid Earth sciences",
        "Environmental sciences",
        "Biogeochemistry",
        "Ocean sciences",
        "Environmental social sciences",
        "Natural hazards",
        "Planetary science",
        "Hydrology",
        "Limnology",
        "Space physics"
    ],
    "Biological sciences": [
        "Cell biology",
        "Biochemistry",
        "Microbiology",
        "Neuroscience",
        "Molecular biology",
        "Genetics",
        "Cancer",
        "Immunology",
        "Biological techniques",
        "Computational biology and bioinformatics",
        "Biotechnology",
        "Biophysics",
        "Structural biology",
        "Ecology",
        "Developmental biology",
        "Evolution",
        "Plant sciences",
        "Physiology",
        "Chemical biology",
        "Systems biology",
        "Drug discovery",
        "Stem cells",
        "Zoology",
        "Psychology"
    ],
    "Health sciences": [
        "Diseases",
        "Medical research",
        "Oncology",
        "Health care",
        "Pathogenesis",
        "Biomarkers",
        "Cardiology",
        "Gastroenterology",
        "Endocrinology",
        "Anatomy",
        "Neurology",
        "Molecular medicine",
        "Risk factors",
        "Rheumatology",
        "Nephrology",
        "Signs and symptoms",
        "Urology",
        "Health occupations"
    ],
    "Scientific community and society": [
        "Social sciences",
        "Scientific community",
        "Energy and society",
        "Agriculture",
        "Developing world",
        "Water resources",
        "Geography",
        "Business and industry",
        "Forestry"
    ]
}